### ISSUE TITLE
Board.get_threads(page=1) raises requests.exceptions.MissingSchema

### ISSUE THREAD

**Issue by irlittz** [bibanon/BASC-py4chan#10]
Not sure why this is happening, but it seems to me that somewhere between calling get_threads(page=1) and the exception occurring some method or function should use self._url of the calling Board instance to create the correct API request URL for the first page, instead the raw page integer value is somehow forwarded to requests which raises this error.

**Comment by rei-gun** [comment]
Hello,

I think I have a similar problem, I'm getting this error when running `derp = basc_py4chan.Board.get_threads(1)`

```[2021-08-03 23:53:04,810] ERROR in app: Exception on /4chan [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/myriad-scraper/server.py", line 19, in scrape4chan
    objList = scrape('a')
  File "/myriad-scraper/src/fourChan/fourChan.py", line 29, in scrape
    derp = basc_py4chan.Board.get_threads(1)
  File "/usr/local/lib/python3.9/site-packages/basc_py4chan/board.py", line 207, in get_threads
    url = self._url.page_url(page)
AttributeError: 'int' object has no attribute '_url'```

I installed and am running with python3. Is this OK?
