### ISSUE TITLE
QPython says all threads have 404'd

### ISSUE THREAD

**Issue by myoung-git** [bibanon/BASC-py4chan#29]
Get this error when downloading any thread using QPython, this has never happened before

`/data/user/0/org.qpython.qpy3/files/bin/qpython3-android5.sh  /storage/emulated/0/qpython/scripts3/pip_console.py  && exit
hon/scripts3/pip_console.py  && exit     <
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/scripts3/pip_console.py", line 1, in <module>
    import os,os.path,sys,readline
ModuleNotFoundError: No module named 'readline'
.4chan.org/b/thread/825365827            <
Starting download
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/data/user/0/org.qpython.qpy3/files/lib/python36.zip/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/data/user/0/org.qpython.qpy3/files/lib/python36.zip/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/data/user/0/org.qpython.qpy3/files/lib/python36.zip/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/data/user/0/org.qpython.qpy3/files/lib/python36.zip/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: NO_CIPHERS_AVAILABLE] no ciphers available (_ssl.c:841)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='a.4cdn.org', port=443): Max retries exceeded with url: /b/thread/825365827.json (Caused by SSLError(SSLError(1, '[SSL: NO_CIPHERS_AVAILABLE] no ciphers available (_ssl.c:841)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy3/files/lib/python36.zip/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/basc_archiver/sites/base.py", line 65, in run
    self.site.download_item(next_item)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/basc_archiver/sites/fourchan.py", line 275, in download_item
    running_thread = running_board.get_thread(thread_id)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/basc_py4chan/board.py", line 130, in get_thread
    thread_id = thread_id
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/requests/sessions.py", line 245, in resolve_redirects
    **adapter_kwargs
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='a.4cdn.org', port=443): Max retries exceeded with url: /b/thread/825365827.json (Caused by SSLError(SSLError(1, '[SSL: NO_CIPHERS_AVAILABLE] no ciphers available (_ssl.c:841)'),))

All threads have either 404'd or no longer exist, exiting.
:/`

**Comment by antonizoon** [comment]
If there's an SSL error, maybe your current environment setup is no longer compatible with the latest Cloudflare mandated security standards? Update everything and tell us how it goes.

https://support.cloudflare.com/hc/en-us/articles/205043158-PCI-compliance-and-Cloudflare-SSL-TLS#h_e037e4bd-baf9-4898-aa24-742e160ddef6

Or maybe its unique to qpython? 

https://github.com/qpython-android/qpython/issues/179

If you are really sure it is our wrapper library that is the issue, try it on a Mac/Linux/Windows Subsystem for Linux Python instance and see how it goes.

**Comment by myoung-git** [comment]
> If there's an SSL error, maybe your current environment setup is no longer compatible with the latest Cloudflare mandated security standards? Update everything and tell us how it goes.
> 
> https://support.cloudflare.com/hc/en-us/articles/205043158-PCI-compliance-and-Cloudflare-SSL-TLS#h_e037e4bd-baf9-4898-aa24-742e160ddef6
> 
> Or maybe its unique to qpython?
> 
> [qpython-android/qpython#179](https://github.com/qpython-android/qpython/issues/179)
> 
> If you are really sure it is our wrapper library that is the issue, try it on a Mac/Linux/Windows Subsystem for Linux Python instance and see how it goes first.

I just realized I put this error in Py4chan instead of the BASC-Archiver, but Pydroid worked! Thank you
